disabled_rules:
- line_length
- trailing_whitespace
- nesting
- function_parameter_count
- function_body_length
- cyclomatic_complexity
- file_length
opt_in_rules:
- empty_count
- empty_string
excluded:
- Pods
- Fillin-iOS/Sources/AppDelegate.swift
- Fillin-iOS/Sources/SceneDelegate.swift
